### ISSUE TITLE
docker run 404

### ISSUE THREAD

**Issue by Walk-Code** [atricore/josso1#69]
I access `http://localhost:8081` appears 404
```sh
docker run \
        --name josso-ee \
        --detach \
        --env JOSSO_CLIENT_ID="idbus-f2f7244e-bbce-44ca-8b33-f5c0bde339f7" \
        --env JOSSO_CLIENT_SECRET="7oUHlv(HLT%vxK4L" \
        --env JOSSO_ADMIN_USR=myadmin \
        --env JOSSO_ADMIN_PWD=changeme \
        --env JOSSO_SKIP_ADMIN_CREATE=false \
        -p8081:8081 -p8101:8101 \
        atricore/josso-ee:latest
```

**Comment by sgonzalezoyuela** [comment]
Hi, 

Thanks for reaching out.  That is ok, after starting a JOSSO/IAM.tf container you don't have any services configured, so a 404 is expected.

JOSSO community edition is now called IAM.tf, you can get documentation on how to get you started with docker, and some examples

## IAM.tf using Docker

https://iam.tf/guide/quick-start.html#run-a-docker-based-example

There are also examples you can get and run using docker compose, that will create all the necessary resources:

## Docker Example: Directory, Basic Authn, SSO Agent
https://iam.tf/guide/examples/example_02.html

I hope this helps
